# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Navi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Navi
  pod 'Alamofire'

  target 'NaviTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NaviUITests' do
    # Pods for testing
  end

end
